# Generated by Django 4.0.2 on 2022-02-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='rent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
