# Generated by Django 4.0.2 on 2022-02-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_list_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='county',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
