# Generated by Django 4.0.2 on 2022-02-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0004_alter_list_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='agent_mail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='agent_mob',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='agent_whats',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='bathroom',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='bedrooms',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='deposit',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Deposit')], default=0),
        ),
    ]
