# Generated by Django 4.0.2 on 2022-02-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0005_list_agent_mail_list_agent_mob_list_agent_whats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='categories',
            field=models.ManyToManyField(related_name='house', to='rentapp.Category'),
        ),
    ]
