# Generated by Django 4.0.2 on 2022-02-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0006_alter_list_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='external',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='internal',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='nearby',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='pets',
            field=models.IntegerField(choices=[(0, 'Not Stated'), (1, 'Allowed')], null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='utility',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='year_built',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='deposit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
