# Generated by Django 4.0.2 on 2022-02-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0007_list_external_list_internal_list_nearby_list_pets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='pets',
            field=models.IntegerField(choices=[('NA', 'Not_Allowed'), ('AD', 'Allowed')], null=True),
        ),
    ]
