# Generated by Django 4.0.2 on 2022-02-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0008_alter_list_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='pets',
            field=models.CharField(choices=[('NA', 'Not_Allowed'), ('AD', 'Allowed')], max_length=2, null=True),
        ),
    ]
