# Generated by Django 4.0.2 on 2022-02-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0009_alter_list_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='pets',
            field=models.CharField(choices=[('Not Allowed', 'Not_Allowed'), ('Allowed', 'Allowed')], max_length=20, null=True),
        ),
    ]
