# Generated by Django 4.0.2 on 2022-02-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0010_alter_list_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='g_maps',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
